// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NanoDMSBusinessService.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NanoDMSBusinessService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NanoDMSBusinessService.Models.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Currency_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Financial_Year_Start_Month")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ntn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Stn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Stock_Accounting_Method")
                        .HasColumnType("uuid");

                    b.Property<string>("Tax3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tax4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Time_Zone_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Location_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Config_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Config_Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Name_Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Business_Id");

                    b.HasIndex("Business_Location_Id");

                    b.ToTable("Business_Config", (string)null);
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("City")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Country")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("DiscountBeforePosCharge")
                        .HasColumnType("integer");

                    b.Property<int>("DiscountBeforeServiceCharge")
                        .HasColumnType("integer");

                    b.Property<int>("DiscountBeforeTax")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PosCharge")
                        .HasColumnType("numeric");

                    b.Property<string>("Postal_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ServiceCharges")
                        .HasColumnType("numeric");

                    b.Property<Guid>("State")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Business_Id");

                    b.ToTable("Business_Location", (string)null);
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessLocationBankSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Bank_Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Bank_Share")
                        .HasColumnType("numeric");

                    b.Property<Guid>("Business_Location_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Merchant_Share")
                        .HasColumnType("numeric");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("Tax_On_Merchant")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tax_Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Business_Location_Id");

                    b.ToTable("BusinessLocationBankSettlements");
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessLocationPsp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Location_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Psp_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Business_Location_Id");

                    b.ToTable("BusinessLocationPsps");
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessLocationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Location_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Business_Id");

                    b.HasIndex("Business_Location_Id");

                    b.ToTable("Business_Location_User", (string)null);
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Business_Id");

                    b.ToTable("Business_User", (string)null);
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessConfig", b =>
                {
                    b.HasOne("NanoDMSBusinessService.Models.Business", "Business")
                        .WithMany("BusinessConfigs")
                        .HasForeignKey("Business_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSBusinessService.Models.BusinessLocation", "BusinessLocation")
                        .WithMany("BusinessConfigs")
                        .HasForeignKey("Business_Location_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("BusinessLocation");
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessLocation", b =>
                {
                    b.HasOne("NanoDMSBusinessService.Models.Business", "Business")
                        .WithMany("BusinessLocations")
                        .HasForeignKey("Business_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessLocationBankSettlement", b =>
                {
                    b.HasOne("NanoDMSBusinessService.Models.BusinessLocation", "Business_Location")
                        .WithMany("BankSettlements")
                        .HasForeignKey("Business_Location_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business_Location");
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessLocationPsp", b =>
                {
                    b.HasOne("NanoDMSBusinessService.Models.BusinessLocation", "Business_Location")
                        .WithMany("Psps")
                        .HasForeignKey("Business_Location_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business_Location");
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessLocationUser", b =>
                {
                    b.HasOne("NanoDMSBusinessService.Models.Business", "Business")
                        .WithMany("BusinessLocationUsers")
                        .HasForeignKey("Business_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSBusinessService.Models.BusinessLocation", "Business_Location")
                        .WithMany("BusinessLocationUsers")
                        .HasForeignKey("Business_Location_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Business_Location");
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessUser", b =>
                {
                    b.HasOne("NanoDMSBusinessService.Models.Business", "Business")
                        .WithMany("BusinessUsers")
                        .HasForeignKey("Business_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.Business", b =>
                {
                    b.Navigation("BusinessConfigs");

                    b.Navigation("BusinessLocationUsers");

                    b.Navigation("BusinessLocations");

                    b.Navigation("BusinessUsers");
                });

            modelBuilder.Entity("NanoDMSBusinessService.Models.BusinessLocation", b =>
                {
                    b.Navigation("BankSettlements");

                    b.Navigation("BusinessConfigs");

                    b.Navigation("BusinessLocationUsers");

                    b.Navigation("Psps");
                });
#pragma warning restore 612, 618
        }
    }
}
