// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NanoDMSAdminService.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NanoDMSAdminService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128082332_RemovedUniqueConstraitCountry")]
    partial class RemovedUniqueConstraitCountry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "budget_limit_type_status", new[] { "unknown", "hourly", "daily", "weekly", "monthly", "yearly" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "campagin_card_bin_status", new[] { "unknown", "active", "inactive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "campagin_status", new[] { "unkown", "active", "inactive", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "change_type_status", new[] { "unknown", "insert", "update", "delete" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "compliance_status", new[] { "unknown", "pending", "approved", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "discount_mode_status", new[] { "unknown", "all", "swipe", "dip", "tap" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "discount_type_status", new[] { "unknown", "percentage", "flat" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "integration_type_status", new[] { "unknown", "direct", "aggregator", "gateway" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "local_international_status", new[] { "unknown", "local", "international" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_type_status", new[] { "unknown", "all", "card", "wallet", "qr" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psp_payment_type_status", new[] { "unknown", "card", "wallet", "bank_transfer", "upi", "qr" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "record_status", new[] { "unknown", "active", "inactive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "settlement_frequency_status", new[] { "unknown", "daily", "weekly", "monthly" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tax_on_merchant_status", new[] { "unknown", "yes", "no" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "terminal_history_status", new[] { "unknown", "active", "inactive", "maintenance", "decommissioned" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NanoDMSAdminService.Models.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Country_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Short_Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Short_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Swift_Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Country_Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Short_Code")
                        .IsUnique();

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Budget_Limit_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int?>("Budget_Limit_Value")
                        .HasColumnType("integer");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Campaign_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Currency_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fbr")
                        .HasColumnType("text");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("Psp_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<decimal?>("Tax_Amount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Campaign_Name");

                    b.HasIndex("Currency_Id");

                    b.HasIndex("Psp_Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CampaignBank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Bank_Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<int?>("Budget_Limit_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int?>("Budget_Limit_Value")
                        .HasColumnType("integer");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Campagin_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("Discount_Mode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Discount_Share")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("Tax_On_Merchant_Share")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Bank_Id");

                    b.HasIndex("Campagin_Id");

                    b.ToTable("Campaign_Banks", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CampaignCardBin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Campagin_Bank_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Campagin_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Card_Bin_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Campagin_Bank_Id");

                    b.HasIndex("Campagin_Id");

                    b.HasIndex("Card_Bin_Id");

                    b.ToTable("Campaign_Card_Bins", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CardBin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Bank_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Card_Bin_Value")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<Guid>("Card_Brand_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Card_Level_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Card_Type_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Country_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("Is_Virtual")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<int?>("Local_International")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Bank_Id");

                    b.HasIndex("Card_Bin_Value")
                        .IsUnique();

                    b.HasIndex("Card_Brand_Id");

                    b.HasIndex("Card_Level_Id");

                    b.HasIndex("Card_Type_Id");

                    b.HasIndex("Country_Id");

                    b.ToTable("Card_Bins", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CardBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Card_Brands", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CardLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Card_Levels", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CardType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Card_Types", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency_Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Currency_Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Flag_Emoji")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Iso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Numeric_Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Phone_Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Time_Zone")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid?>("Country_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Country_Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.DiscountRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Applicable_Days")
                        .HasColumnType("text");

                    b.Property<int?>("Budget_Limit_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int?>("Budget_Limit_Value")
                        .HasColumnType("integer");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Campaign_Card_Bin_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("Discount_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Discount_Value")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("End_Time")
                        .HasColumnType("interval");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Max_Discount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Min_Spend")
                        .HasColumnType("numeric");

                    b.Property<int?>("Payment_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Start_Time")
                        .HasColumnType("interval");

                    b.Property<int?>("Transaction_Cap")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Campaign_Card_Bin_Id");

                    b.ToTable("Discount_Rules", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.DiscountRuleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Applicable_Days")
                        .HasColumnType("text");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Campaign_Card_Bin_Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Change_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Currency_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Discount_Rule_Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Discount_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Discount_Value")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Max_Discount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Min_Spend")
                        .HasColumnType("numeric");

                    b.Property<int?>("Payment_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("Stackable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Transaction_Cap")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Campaign_Card_Bin_Id");

                    b.HasIndex("Currency_Id");

                    b.HasIndex("Discount_Rule_Id");

                    b.ToTable("Discount_Rule_Histories", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PosTerminalAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Assigned_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Mid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PosTerminal_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Unassigned_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PosTerminal_Id");

                    b.HasIndex("Tid")
                        .IsUnique();

                    b.ToTable("Pos_Terminal_Assignments", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PosTerminalConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Config_Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Config_Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Pos_Terminal_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Config_Key")
                        .IsUnique();

                    b.HasIndex("Pos_Terminal_Id");

                    b.ToTable("Pos_Terminal_Configurations", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PosTerminalMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Model_Number")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Serial_Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Software_Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Terminal_Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Serial_Number")
                        .IsUnique();

                    b.ToTable("Pos_Terminal_Masters", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PosTerminalStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("Pos_Terminal_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Pos_Terminal_Id");

                    b.ToTable("Pos_Terminal_Status_Histories", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Psp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Api_Endpoint")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Api_Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Compliance_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Contact_Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Contact_Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("Country_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency_Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Currency_Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("Daily_Volume_Limit")
                        .HasColumnType("numeric");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Documentation_Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Integration_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Onboarded_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("Onboarded_By")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Psp_Category_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Reg_Doc_Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Registration_Number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Requires_Kyc")
                        .HasColumnType("boolean");

                    b.Property<int?>("Risk_Score")
                        .HasColumnType("integer");

                    b.Property<string>("Sandbox_Endpoint")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Settlement_Frequency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Short_Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Supported_Currencies")
                        .HasColumnType("text");

                    b.Property<string>("Supported_Payment_Methods")
                        .HasColumnType("text");

                    b.Property<decimal?>("Transaction_Limit")
                        .HasColumnType("numeric");

                    b.Property<string>("Webhook_Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Country_Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Psp_Category_Id");

                    b.ToTable("Psps");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PspCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Psp_Categories", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PspCurrency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Currency_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Psp_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Currency_Id");

                    b.HasIndex("Psp_Id", "Currency_Id")
                        .IsUnique();

                    b.ToTable("Psp_Currencies", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PspDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Doc_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Doc_Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Psp_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Psp_Id");

                    b.ToTable("Psp_Documents", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PspPaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessLocation_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Business_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Create_User")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Update_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Last_Update_User")
                        .HasColumnType("uuid");

                    b.Property<int?>("Payment_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("Psp_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Psp_Id");

                    b.ToTable("Psp_Payment_Methods", (string)null);
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Bank", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.Country", "Country")
                        .WithMany("Banks")
                        .HasForeignKey("Country_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Campaign", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("Currency_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSAdminService.Models.Psp", "Psps")
                        .WithMany("Campaigns")
                        .HasForeignKey("Psp_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Psps");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CampaignBank", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.Bank", "Bank")
                        .WithMany("Campaign_Banks")
                        .HasForeignKey("Bank_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSAdminService.Models.Campaign", "Campaign")
                        .WithMany("CampaignBanks")
                        .HasForeignKey("Campagin_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CampaignCardBin", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.CampaignBank", "Campaign_Bank")
                        .WithMany("Campaign_Card_Bins")
                        .HasForeignKey("Campagin_Bank_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSAdminService.Models.Campaign", "Campaign")
                        .WithMany("CampaignCardBins")
                        .HasForeignKey("Campagin_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSAdminService.Models.CardBin", "Card_Bin")
                        .WithMany("Campaign_Card_Bins")
                        .HasForeignKey("Card_Bin_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Campaign_Bank");

                    b.Navigation("Card_Bin");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CardBin", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.Bank", "Bank")
                        .WithMany("Card_Bins")
                        .HasForeignKey("Bank_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSAdminService.Models.CardBrand", "Card_Brand")
                        .WithMany("Card_Bins")
                        .HasForeignKey("Card_Brand_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSAdminService.Models.CardLevel", "Card_Level")
                        .WithMany("Card_Bins")
                        .HasForeignKey("Card_Level_Id");

                    b.HasOne("NanoDMSAdminService.Models.CardType", "Card_Type")
                        .WithMany("Card_Bins")
                        .HasForeignKey("Card_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSAdminService.Models.Country", "Country")
                        .WithMany("Card_Bins")
                        .HasForeignKey("Country_Id");

                    b.Navigation("Bank");

                    b.Navigation("Card_Brand");

                    b.Navigation("Card_Level");

                    b.Navigation("Card_Type");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Currency", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.Country", "Country")
                        .WithMany("Currencies")
                        .HasForeignKey("Country_Id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.DiscountRule", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.CampaignCardBin", "CampaignCardBin")
                        .WithMany("Discount_Rules")
                        .HasForeignKey("Campaign_Card_Bin_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignCardBin");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.DiscountRuleHistory", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.CampaignCardBin", "CampaignCardBin")
                        .WithMany("Discount_Rule_Histories")
                        .HasForeignKey("Campaign_Card_Bin_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSAdminService.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("Currency_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSAdminService.Models.DiscountRule", "DiscountRule")
                        .WithMany("Discount_Rule_Histories")
                        .HasForeignKey("Discount_Rule_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignCardBin");

                    b.Navigation("Currency");

                    b.Navigation("DiscountRule");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PosTerminalAssignment", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.PosTerminalMaster", "Pos_Terminal")
                        .WithMany("PosTerminal_Assignments")
                        .HasForeignKey("PosTerminal_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pos_Terminal");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PosTerminalConfiguration", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.PosTerminalMaster", "Pos_Terminal")
                        .WithMany("PosTerminal_Configurations")
                        .HasForeignKey("Pos_Terminal_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pos_Terminal");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PosTerminalStatusHistory", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.PosTerminalMaster", "Pos_Terminal")
                        .WithMany("PosTerminal_Status_Histories")
                        .HasForeignKey("Pos_Terminal_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pos_Terminal");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Psp", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.Country", "Country")
                        .WithMany("Psps")
                        .HasForeignKey("Country_Id");

                    b.HasOne("NanoDMSAdminService.Models.PspCategory", "PspCategory")
                        .WithMany("Psps")
                        .HasForeignKey("Psp_Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("PspCategory");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PspCurrency", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.Currency", "Currency")
                        .WithMany("Psp_Currencies")
                        .HasForeignKey("Currency_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanoDMSAdminService.Models.Psp", "Psp")
                        .WithMany("PspCurrencies")
                        .HasForeignKey("Psp_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Psp");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PspDocument", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.Psp", "Psp")
                        .WithMany("PspDocuments")
                        .HasForeignKey("Psp_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psp");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PspPaymentMethod", b =>
                {
                    b.HasOne("NanoDMSAdminService.Models.Psp", "Psp")
                        .WithMany("PspPaymentMethods")
                        .HasForeignKey("Psp_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psp");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Bank", b =>
                {
                    b.Navigation("Campaign_Banks");

                    b.Navigation("Card_Bins");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Campaign", b =>
                {
                    b.Navigation("CampaignBanks");

                    b.Navigation("CampaignCardBins");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CampaignBank", b =>
                {
                    b.Navigation("Campaign_Card_Bins");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CampaignCardBin", b =>
                {
                    b.Navigation("Discount_Rule_Histories");

                    b.Navigation("Discount_Rules");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CardBin", b =>
                {
                    b.Navigation("Campaign_Card_Bins");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CardBrand", b =>
                {
                    b.Navigation("Card_Bins");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CardLevel", b =>
                {
                    b.Navigation("Card_Bins");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.CardType", b =>
                {
                    b.Navigation("Card_Bins");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Country", b =>
                {
                    b.Navigation("Banks");

                    b.Navigation("Card_Bins");

                    b.Navigation("Currencies");

                    b.Navigation("Psps");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Currency", b =>
                {
                    b.Navigation("Psp_Currencies");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.DiscountRule", b =>
                {
                    b.Navigation("Discount_Rule_Histories");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PosTerminalMaster", b =>
                {
                    b.Navigation("PosTerminal_Assignments");

                    b.Navigation("PosTerminal_Configurations");

                    b.Navigation("PosTerminal_Status_Histories");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.Psp", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("PspCurrencies");

                    b.Navigation("PspDocuments");

                    b.Navigation("PspPaymentMethods");
                });

            modelBuilder.Entity("NanoDMSAdminService.Models.PspCategory", b =>
                {
                    b.Navigation("Psps");
                });
#pragma warning restore 612, 618
        }
    }
}
